### ISSUE TITLE
Hello, Problem Listing Animals

### ISSUE THREAD

**Issue by damianrivadulla** [PRDeltoid/Petpoint-Webservices#8]
Hello, i'm using your plugin, but i can't get the individual animal view.

I think i'm doing something wrong. Do you know what can be happening?
dogs link: http://1pr.180.myftpupload.com/meet-our-pets-dogs/
dogs example link: http://1pr.180.myftpupload.com/animals/?id=37044802/

Thanks!!

**Comment by PRDeltoid** [comment]
I apologize for not getting to this sooner. My notifications were muted for this project and I didn't realize it had pending issues.

I realize it's almost 2 years late and I assume you've moved on, but if you still want to give this plugin a try, I am happy to help troubleshoot your issue.

I believe the issue here is that your value for the "URL of View Animals page" setting has a trailing forward slash. This is causing the ID in the URL to be ignored, and no animal is loaded if the ID is missing.

If you are still interesting in using this plugin, you can try to remove the trailing forward slash in the setting URL so it reads "http://1pr.180.myftpupload.com/animals". 

When I have access to auth key for development I will be working on a fix so that any trailing forward slash is automatically removed so this won't be a problem for future users. Waiting to hear back from PetPoint.

**Comment by Finagar** [comment]
I am having the same problem this person is having. I know it has been a while since the last time this was updated so this is definitely a long sot.

**Comment by PRDeltoid** [comment]
I believe this has been fixed in the most recent update.
