### ISSUE TITLE
Local Development - Can I test

### ISSUE THREAD

**Issue by tazcrzy** [PRDeltoid/Petpoint-Webservices#9]
I am in the processing a creating a new website for our Shelter instead of a custom one that is terrible to manage.  I am trying to pull in PetPoint with the plugin - will it work in a locally developed site for now?

**Comment by tazcrzy** [comment]
I need some help with your plugin - why won't you respond?

**Comment by PRDeltoid** [comment]
I apologize for the delay, I didn't have notifications on for this repository and didn't see your issue here.

I believe this plugin should work fine with local development as long as you have an auth key for PetPoint setup. The requests to PetPoints API must not be blocked or the pages will fail to load as well. 

Were you able to determine if this plugin was usable during local Wordpress development? This info may help future users.
